#!/bin/sh

#
# Install a .fw image to disk
#
# To use this, copy the .fw file that you want on the disk device to the
# data partition and call it install.fw. If you want to do the
# installation yourself, copy a shell script called install.sh over.
#

LOADER_DATA_DEV=""
LOADER_DEV=""
FWIMAGE=/mnt/install.fw
USER_SCRIPT=/mnt/install.sh
# flash on internal hard disk drive
# The first one found will be used
INTERNAL_DEVICE_KERNEL="nvme0n1 sda sdb mmcblk0 mmcblk1 hda hdb vda vdb"

mount_filesystems() {
    # mount efi vars
    if [ -d /sys/firmware/efi ]; then
        mount -t efivarfs efivarfs /sys/firmware/efi/efivars
    fi

    while ! findfs LABEL=LOADER_DATA; do
        echo "Waiting for LOADER_DATA to be available..."
        sleep 1
    done

    LOADER_DATA_DEV="$(findfs LABEL=LOADER_DATA)"
    LOADER_DEV=$(lsblk $LOADER_DATA_DEV -no pkname)

    # mount data partition
    mount -t vfat -o ro $LOADER_DATA_DEV /mnt

    if [ $? -ne 0 ]; then
        echo "Mounting failed! Not powering off so that the system can be debugged."
        exit 1
    fi
}

install_ourselves() {
    echo "Running fwup to install $FWIMAGE..."

    DESTINATION=""
    for d in $INTERNAL_DEVICE_KERNEL; do
        if [ "$LOADER_DEV" = "$d" ]; then
            echo "$d is our install media, skip it..."
            continue
        fi
        if [ -e "/dev/$d" ]; then
            echo "found destination: /dev/$d"
            DESTINATION="/dev/$d"
            break
        fi
    done

    if [ -z "$DESTINATION" ]; then
        echo "Could not find destination drive! Not powering off so that the system can be debugged."
        exit 1
    fi

    echo
    echo "Starting install in 5s..."
    sleep 5

    /usr/bin/fwup -a -i $FWIMAGE -d $DESTINATION -t complete

    if [ $? -ne 0 ]; then
        echo "Installation failed! Not powering off so that the system can be debugged."
        exit 1
    fi

    if [ -d /sys/firmware/efi ]; then
		echo "Configuring EFI boot"
        efibootmgr -B -b 0001
        # The forward slashes on the loader are important. Without them efibootmgr was
        # doubling up the backslashes and that wouldn't boot.
        efibootmgr -c -b 0001 -d $DESTINATION -L Nerves -l /EFI/BOOT/bootx64.efi -u 'initrd=\\EFI\\BOOT\\nerves_initramfs'
        if [ $? -ne 0 ]; then
            echo "Installation failed! Not powering off so that the system can be debugged."
            exit 1
        fi
        efibootmgr --bootorder 0001

        # Clean up other entries if they exist
        efibootmgr -B -b 0000
        efibootmgr -B -b 0002
        efibootmgr -B -b 0003
        efibootmgr -B -b 0004
        efibootmgr -B -b 0005
	fi
}

install_user() {
    echo "Running $USER_SCRIPT..."
    cd /mnt
    sh $USER_SCRIPT
    if [ $? -ne 0 ]; then
        echo "Installation failed! Not powering off so that the system can be debugged."
        exit 1
    fi
}

install() {
    mount_filesystems
    if [ -e $USER_SCRIPT ]; then
        install_user
    else
        install_ourselves
    fi

    cd /
    umount /mnt

    echo
    echo
    echo
    echo
    echo "Installation successful!!"
    echo
    echo "Remove the USB drive and the device will reboot in 10 seconds..."

    sleep 10
    echo "Rebooting..."

    reboot
}

case "$1" in
    start)
        install
        ;;
    stop)
        ;;

    *)
        # Don't handle any other conditions
        exit 0
esac
